export enum Roles {

    ROLE_CLIENT = 'ROLE_CLIENT',
    ROLE_CORRESPONDANT = 'ROLE_CORRESPONDANT',
    ROLE_SPECIALISTE = 'ROLE_SPECIALISTE',
    ROLE_CDP = 'ROLE_CDP',
    ROLE_PILOTEDA = 'ROLE_PILOTEDA',
    ROLE_ADMIN = 'ROLE_ADMIN'
}
